// Official TikTok Shop 3rd Level Child Categories Taxonomy
// Synchronized with frontend CATEGORY_CONFIG (Source of Truth)
// Excludes "Todas"

export const OFFICIAL_TIKTOK_CHILD_CATEGORIES: Record<string, Record<string, string[]>> = {
  "Acessórios de moda": {
    "Acessórios para cabelos": [
      "Grampos e alfinetes de cabelo",
      "Faixas e elásticos de cabelo",
      "Tiaras",
      "Conjuntos de acessórios para cabelo",
      "Acessórios de cabeça e coroas",
      "Modeladores de cabelo"
    ],
    "Acessórios para roupas": [
      "Cintos",
      "Cachecóis e xales",
      "Gravatas e gravatas-borboleta",
      "Luvas",
      "Lenços",
      "Abotoaduras",
      "Protetores de ouvido",
      "Máscaras e acessórios faciais",
      "Conjuntos de acessórios de moda"
    ],
    "Bijuterias e acessórios": [
      "Colares",
      "Chaveiros",
      "Tornozeleiras",
      "Pulseiras e braceletes",
      "Conjuntos de joias",
      "Brincos",
      "Joias corporais",
      "Anéis",
      "Amuletos e pingentes",
      "Ajustadores e protetores de joias"
    ],
    "Chapéus": [],
    "Coleiras e broches": [
      "Coleiras",
      "Broches"
    ],
    "Extensões de cabelo e perucas": [
      "Extensões de cabelo humano",
      "Extensões sintéticas",
      "Perucas de cabelo humano",
      "Perucas sintéticas",
      "Perucas frontais",
      "Perucas de renda",
      "Perucas para fantasias"
    ],
    "Óculos": [
      "Óculos de sol",
      "Armações e óculos",
      "Estojos e acessórios para óculos"
    ],
    "Relógios e acessórios": [
      "Relógios masculinos",
      "Relógios femininos",
      "Relógios unissex",
      "Relógios de casal",
      "Acessórios para relógio"
    ],
    "Tecidos para costura": [
      "Veludo",
      "Seda e cetim",
      "Couro",
      "Poliéster",
      "Algodão",
      "Renda",
      "Batik",
      "Tela",
      "Jeans",
      "Lã"
    ],
    "Acessórios para casamento": [
      "Véus de noiva",
      "Acessórios de cabeça para noiva",
      "Jaquetas e capas para casamento",
      "Luvas de noiva",
      "Cintos de noiva",
      "Corsages de pulso",
      "Boutonnieres",
      "Acessórios para noivo"
    ]
  },
  "Alimentos e bebidas": {
    "Comida instantânea": [
      "Legumes em conserva, picles e chutney",
      "Macarrão instantâneo",
      "Cereais matinais, granola e aveia",
      "Alimentos enlatados, em frascos e embalados",
      "Hot pot instantâneo",
      "Arroz e mingau instantâneos"
    ],
    "Bebidas": [
      "Bebidas esportivas e energéticas",
      "Misturas para bebidas em pó",
      "Chá",
      "Café",
      "Substituição de refeições e bebidas proteicas",
      "Xaropes e concentrados",
      "Sucos e smoothies",
      "Refrigerantes",
      "Refrigerante e água com gás",
      "Coberturas para bebidas",
      "Água e água aromatizada",
      "Bebidas de chocolate e malte",
      "Bebidas sem álcool",
      "Substitutos do café",
      "Substituto do leite"
    ],
    "Lanches": [
      "Chocolate e lanches de chocolate",
      "Goma de mascar e chiclete",
      "Barras",
      "Doces",
      "Biscoitos, cookies e wafers",
      "Batatas fritas e salgadinhos recheados",
      "Snacks secos",
      "Nozes e ervilhas",
      "Sementes",
      "Pipoca",
      "Pudins de creme e geleia",
      "Kits para presente",
      "Bolos e doces para lanche",
      "Algas marinhas",
      "Lanches vegetarianos e com glúten"
    ],
    "Produtos básicos e essenciais para cozinhar": [
      "Ervas, especiarias e temperos",
      "Açúcar e adoçantes",
      "Sal",
      "Molhos de cozinha",
      "Farinha",
      "Compotas, molhos e pastas",
      "Caldo, molho e sopa instantânea",
      "Óleos",
      "Mel e xarope de ácer",
      "Vinagre",
      "Pastas de cozinha e kits de temperos",
      "Intensificadores de sabor",
      "Massa, macarrão e vermicelli",
      "Arroz",
      "Alimentos secos",
      "Feijões e grãos",
      "Vinho para cozinhar",
      "Óleos infusionados"
    ],
    "Panificação": [
      "Gordura vegetal",
      "Misturas para panificação",
      "Farinha para panificação",
      "Fermento em pó e bicarbonato de sódio",
      "Marshmallows",
      "Corante alimentar",
      "Cobertura, glacê e decorações",
      "Aromatizantes e extratos de alimentos",
      "Pão ralado e recheio",
      "Bolos e tortas",
      "Pão",
      "Pastelaria"
    ],
    "Leite e laticínios": [
      "Leite condensado",
      "Cremes",
      "Queijo e queijo em pó",
      "Manteiga e margarina",
      "Creme",
      "Leite evaporado",
      "Leite em pó",
      "Leite não lácteo",
      "Leite UHT",
      "Sorvete"
    ],
    "Alimentos frescos e congelados": [
      "Refeições preparadas",
      "Kits de refeições",
      "Tofu",
      "Alternativas à carne para vegetarianos",
      "Pizza e focaccia",
      "Comida congelada",
      "Massas e molhos",
      "Sopas e ensopados"
    ],
    "Cerveja, vinho e destilados": [
      "Bebidas espirituosas"
    ]
  },
  "Automotivo e moto": {
    "Acessórios interiores de veículos": [
      "Fragrâncias para carros",
      "Montagens e suportes",
      "Decorações de veículos",
      "Estufagem e arrumação",
      "Tapetes para veículos",
      "Molduras interiores",
      "Tapetes antiderrapantes",
      "Capas de volante",
      "Adesivos internos",
      "Fechos e clipes",
      "Racks traseiros e acessórios",
      "Almofadas de pescoço",
      "Estojos para chaves de carro",
      "Almofadas de assento",
      "Alavancas de câmbio e pedais",
      "Segurança e travas de volante",
      "Cuidados com interior"
    ],
    "Lavagem e manutenção de carros": [
      "Líquidos de limpeza e cuidados",
      "Pistolas de água e lanças de espuma",
      "Acessórios para lavagem de veículos",
      "Cuidados com motor",
      "Reparo de janelas",
      "Lavadores de veículos",
      "Ferramentas de pintura e reparo de janelas",
      "Cuidados com pintura",
      "Máquinas de polir e acessórios"
    ],
    "Ferramentas de reparo de veículos": [
      "Ferramentas de escape",
      "Ferramentas de reparo e montagem de pneus",
      "Ferramentas de diagnóstico",
      "Ferramentas de reparo de motores e transmissões",
      "Ferramentas de inspeção de veículos",
      "Ferramentas de montagem e desmontagem",
      "Ferramentas de reparo de carroceria",
      "Ferramentas de reparo de bateria",
      "Leitores e scanners de código",
      "Ferramentas de chapa metálica"
    ],
    "Sistema eletrônico de veículos": [
      "Carregadores USB",
      "Reprodutores de vídeo para carros",
      "Videovigilância",
      "Eletrodomésticos para carros",
      "Dispositivos de áudio de veículos",
      "Câmeras para carros",
      "Transmissores FM e Bluetooth",
      "Acessórios eletrônicos",
      "GPS e acessórios",
      "Sistemas inteligentes",
      "Sistemas de alarme e segurança"
    ],
    "Luzes do veículo": [
      "Luzes decorativas",
      "Barras de luz e luzes de trabalho",
      "Fios",
      "Bases"
    ],
    "Acessórios exteriores de veículos": [
      "Coberturas",
      "Adesivos de carros",
      "Guarda-sóis",
      "Topos para antenas",
      "Buzinas e acessórios",
      "Películas e proteção solar",
      "Acessórios e acabamentos cromados",
      "Suportes",
      "Faixas refletoras",
      "Decoração",
      "Kits dobráveis para retrovisores laterais",
      "Coberturas e abrigos para veículos",
      "Placas",
      "Suportes para selo/imposto do veículo",
      "Películas para vidros",
      "Palas de lama e protetores contra respingos",
      "Visores e defletores de janela lateral"
    ],
    "Acessórios e peças para motos": [
      "Equipamentos de proteção",
      "Travas e segurança",
      "Adesivos e películas para motos",
      "Assentos e capas de assento",
      "Carpetes",
      "Acessórios para motos",
      "Roupas e capas para motos",
      "Caixas e estojos",
      "Jaquetas e capas de chuva",
      "Capacetes",
      "Para-lamas e protetores contra respingos",
      "Transporte e armazenamento"
    ],
    "Quadriciclos, motorhomes e barcos": [
      "Peças e acessórios para motorhomes"
    ],
    "Peças de reposição automotivas": [
      "Pneus e acessórios",
      "Carroceria, estrutura e para-choques",
      "Limpadores e lavadores de para-brisa",
      "Rodas, aros e acessórios",
      "Amortecedores, suportes e suspensão",
      "Baterias e acessórios",
      "Sistemas de combustível",
      "Radiadores, arrefecimento e climatização",
      "Espelhos e acessórios",
      "Molduras e acessórios"
    ],
    "Peças de motos": [
      "Rodas, aros e acessórios",
      "Buzinas e acessórios",
      "Amortecedores, suportes e suspensão",
      "Escapes e emissões",
      "Cabos e tubos",
      "Sistemas de frenagem",
      "Luzes do veículo",
      "Baterias e acessórios"
    ]
  },
  "Bebê e maternidade": {
    "Cuidados com bebê e saúde": [
      "Toalhetes e suportes",
      "Cuidados com a pele do bebê",
      "Chupetas, mordedores e alívio de dentição",
      "Detergente para roupa",
      "Banheiras e assentos de banho para bebês",
      "Cuidados nasais e orais",
      "Cuidados com cabelo e sabonete líquido",
      "Ferramentas de beleza e cuidados para bebês",
      "Suprimentos de banho para bebês",
      "Fragrâncias",
      "Tesouras de cabelo para bebês",
      "Fraldas",
      "Balanças",
      "Toalhas e toucas de banho",
      "Desinfetante de mãos para bebês",
      "Distribuidores de remédios",
      "Fabricantes de mãos e pegadas",
      "Esterilizadores de roupas para bebês",
      "Secadores de cabelo para bebês",
      "Dispositivos de medição de altura e circunferência da cabeça"
    ],
    "Roupas e sapatos para bebês": [
      "Kits para presente",
      "Sapatos",
      "Pijamas",
      "Peças para parte superior",
      "Bodys e maiôs",
      "Roupas de banho",
      "Peças para parte inferior",
      "Bloomers, capas de fraldas e roupas íntimas",
      "Jaquetas e casacos",
      "Meias e meia-calças",
      "Fantasias",
      "Vestidos",
      "Moletons e roupas esportivas",
      "Macacões"
    ],
    "Móveis para bebês": [
      "Bacio e assento de aprendizagem",
      "Cadeirinhas, saltadores e balanços",
      "Berços e camas",
      "Cadeiras de bebê",
      "Andadores",
      "Colchões e roupas de cama",
      "Mesas de troca",
      "Cadeiras altas, assentos e acessórios",
      "Armazenamento",
      "Cercados",
      "Decoração",
      "Mesas e escrivaninhas para bebês",
      "Conjuntos de móveis"
    ],
    "Suprimentos para maternidade": [
      "Roupas e acessórios para gestantes",
      "Almofadas de maternidade",
      "Cintos de apoio",
      "Vitaminas e suplementos para maternidade",
      "Cintos de segurança e acessórios para gestantes",
      "Roupas íntimas para gestantes",
      "Cuidados com a pele para gestantes",
      "Roupas para amamentação"
    ],
    "Brinquedos para bebês": [
      "Educação infantil e brinquedos inteligentes",
      "Cercados",
      "Brinquedos de banho",
      "Playgins e tapetes para brincar",
      "Bolas",
      "Bonecas e ursos de pelúcia",
      "Brinquedos sonoros para bebês",
      "Cadeiras de carro e brinquedos para carrinhos de bebê",
      "Esportes para bebês e brincadeiras ao ar livre",
      "Brinquedos elétricos e de controle remoto para bebês",
      "Kits para presente",
      "Escalada em ambiente interno e estruturas para brincar",
      "Figuras e modelos de brinquedos",
      "Brincadeira de bebê",
      "Cavalos e animais de balanço",
      "Espelhos",
      "Brinquedos Roly-Poly"
    ],
    "Segurança de bebês": [
      "Portões e portas",
      "Monitores",
      "Travas e correias de segurança",
      "Grades e protetores de cama",
      "Mosquiteiro",
      "Protetores de borda e canto",
      "Proteção contra choque elétrico"
    ],
    "Artigos essenciais para viagens de bebês": [
      "Porta-bebês",
      "Carrinhos de bebê",
      "Arnês e rédeas para crianças",
      "Bolsas para fraldas",
      "Acessórios para carrinhos de bebê",
      "Cintos de segurança e acessórios",
      "Assentos de bebê para veículos",
      "Acessórios para cadeirinhas infantis"
    ],
    "Acessórios fashion para bebês": [
      "Babadores e panos de arroto",
      "Bolsas de bebê",
      "Chapéus para bebês",
      "Luvas para bebês",
      "Acessórios de cabelo para bebês",
      "Protetores de ouvido para bebês",
      "Óculos de sol",
      "Máscaras faciais para bebês",
      "Lenços para bebês",
      "Bijuterias para bebês",
      "Kits para presente"
    ],
    "Enfermagem e alimentação": [
      "Utensílios para bebês",
      "Aquecedores, refrigeradores e esterilizadores de mamadeiras",
      "Mamadeiras e acessórios",
      "Processadores de alimentos",
      "Limpeza de mamadeiras",
      "Armazenamento e organização de fórmulas e leites",
      "Capas para amamentação",
      "Absorventes para seios",
      "Chupetas",
      "Almofadas de amamentação",
      "Caixas para mamadeira e escorredores"
    ]
  },
  "Beleza e cuidados pessoais": {
    "Cuidados com as mãos e os pés": [
      "Ferramentas de manicure e pedicure",
      "Tratamentos de unhas",
      "Loções, cremes e esfoliantes para as mãos",
      "Controle de odor nos pés",
      "Acessórios e decoração de unhas",
      "Lavagem das mãos",
      "Kits de arte para unhas",
      "Arte para unhas e esmaltes",
      "Máscaras para mãos e pés",
      "Removedores de esmalte",
      "Desinfetantes para as mãos",
      "Produtos para remoção de cera"
    ],
    "Cuidados com os olhos e ouvidos": [
      "Máscaras para dormir",
      "Tampões para os ouvidos",
      "Otoscópios eletrônicos"
    ],
    "Itens de cuidados pessoais": [
      "Dispositivos de beleza corporal",
      "Modeladores e alisadores de cabelo",
      "Secadores de cabelo",
      "Acessórios",
      "Dispositivos de massagem",
      "Escovas de dentes elétricas",
      "Aparadores e máquinas de cortar cabelo",
      "Dispositivos de remoção de pelos",
      "Barbeadores elétricos",
      "Modeladores elétricos de sobrancelhas",
      "Irrigadores orais",
      "Dispositivos de beleza facial",
      "Aparadores de pelos corporais",
      "Aparadores de pelos de nariz e ouvido",
      "Almofadas térmicas",
      "Cadeiras de massagem"
    ],
    "Maquiagem": [
      "Delineadores para olhos e lábios",
      "Batons e brilhos labiais",
      "Produtos para sobrancelhas",
      "Maquiagem corporal",
      "Conjuntos de maquiagem",
      "Cílios postiços e adesivos",
      "Sombras",
      "Corretivos e bases",
      "Rímel",
      "Pó",
      "Blush",
      "Pincéis de maquiagem",
      "Utensílios de maquiagem",
      "BB e CC Cream",
      "Tatuagens temporárias",
      "Bronzeadores e iluminadores",
      "Removedores de maquiagem",
      "Spray fixador",
      "Curvadores de cílios",
      "Bases e primers",
      "Esponjas de maquiagem",
      "Espelhos de maquiagem",
      "Hastes flexíveis de algodão",
      "Primers para cílios",
      "Esponjas para pó",
      "Máquinas e kits de tatuagem"
    ],
    "Fragrâncias": [
      "Perfume masculino",
      "Perfume feminino",
      "Perfume unissex",
      "Kits de perfume"
    ],
    "Cuidados com a pele": [
      "Tratamentos labiais",
      "Hidratantes e brumas",
      "Ferramentas de cuidados com a pele",
      "Limpadores faciais",
      "Séruns e essências",
      "Kits de cuidados com a pele",
      "Tratamentos para os olhos",
      "Máscaras faciais",
      "Esfoliantes e peelings faciais",
      "Tratamentos para acne",
      "Protetor solar facial",
      "Tônicos",
      "Tratamentos nasais",
      "Cremes de massagem facial"
    ],
    "Cuidados com cabelos e penteados": [
      "Ferramentas de modelagem sem calor",
      "Shampoo e condicionador",
      "Produtos para queda de cabelo",
      "Pentes e escovas",
      "Tintura para cabelo",
      "Mobiliário para cabeleireiros",
      "Tratamentos para couro cabeludo",
      "Permanentes e texturizadores",
      "Tratamentos contra piolhos",
      "Relaxantes capilares",
      "Mousse e gel",
      "Tratamentos para cabelo e couro cabeludo",
      "Pó modelador para cabelo"
    ],
    "Cuidados nasais e orais": [
      "Limpeza nasal",
      "Pasta de dentes",
      "Clareamento dos dentes",
      "Spray oral",
      "Escovas de dente",
      "Fio dental e palhetas",
      "Limpadores de língua",
      "Enxaguante bucal",
      "Cuidados com dentaduras",
      "Kits de cuidado oral",
      "Protetores contra ranger os dentes",
      "Acessórios ortodônticos"
    ],
    "Banho e cuidados com o corpo": [
      "Cremes e loções corporais",
      "Gel de banho e sabonete corporal",
      "Depilação e barbear corporal",
      "Kits de cuidado corporal",
      "Cuidados com o pescoço",
      "Óleo corporal e de massagem",
      "Cuidados pós-tatuagem",
      "Desodorantes e antitranspirantes",
      "Cremes modeladores corporais",
      "Acessórios de banho",
      "Esfoliantes e peelings corporais",
      "Bronzeadores e autobronzeadores",
      "Talco",
      "Protetor solar corporal",
      "Ferramentas manuais de massagem",
      "Máscaras corporais",
      "Cuidados com os seios"
    ],
    "Cuidados pessoais especiais": [
      "Adesivos térmicos",
      "Repelentes de insetos",
      "Bolsas de gelo",
      "Protetores de cama para incontinência",
      "Fraldas para adultos"
    ],
    "Cuidados masculinos": [
      "Espuma de barbear e pós-barba",
      "Cuidados com a pele masculina",
      "Cuidados com o cabelo masculino",
      "Banho e corpo masculino",
      "Navalhas",
      "Desodorantes masculinos",
      "Cuidados masculinos",
      "Maquiagem masculina",
      "Conjuntos de barbear",
      "Acessórios de barbear manual",
      "Cuidados íntimos masculinos"
    ],
    "Cuidados femininos": [
      "Higiene feminina",
      "Cremes vaginais",
      "Desodorantes íntimos",
      "Absorventes",
      "Copos menstruais",
      "Tampões",
      "Roupas íntimas menstruais"
    ]
  },
  "Brinquedos e passatempos": {
    "Brinquedos clássicos e inovadores": [
      "Novidades e brinquedos divertidos",
      "Figuras de ação e brinquedos",
      "Modelos e veículos de brinquedo",
      "Brinquedos para aliviar o estresse",
      "Brinquedos de construção",
      "Brinquedos cápsulas",
      "Brinquedos de slime e moles",
      "Jogo de faz de conta",
      "Brinquedos de agitação e dedo",
      "Piões",
      "Fantoches e teatros de fantoches",
      "Ioiôs"
    ],
    "Bonecas e ursos de pelúcia": [
      "Bonecos de pelúcia",
      "Bonecas",
      "Acessórios para bonecas",
      "Casas de bonecas e conjuntos de brinquedos"
    ],
    "Jogos e quebra-cabeças": [
      "Jogos de empilhar",
      "Jogos de tabuleiro",
      "Jogos de cartas",
      "Dados",
      "Jogos de chão",
      "Quebra-cabeças",
      "Cubos mágicos",
      "Equipamentos de magia e acrobacia"
    ],
    "Esportes e brincadeiras ao ar livre": [
      "Brinquedos para piscina, água e areia",
      "Brinquedos de passeio",
      "Bolhas",
      "Detonadores e armas de brinquedo",
      "Brinquedos voadores",
      "Equipamento de parquinho",
      "Brinquedos esportivos",
      "Salas recreativas, tendas e túneis",
      "Espadas e sabres de brinquedo",
      "Brinquedos de exploração da natureza",
      "Pipas e cata-ventos",
      "Jogos de mármore"
    ],
    "Brinquedos educativos": [
      "Cartão didático",
      "Brinquedos de ciência e tecnologia",
      "Brinquedos de matemática",
      "Tablets de brinquedo e computadores",
      "Artes e ofícios",
      "Brinquedos de linguagem",
      "Classificadores de formas",
      "Brinquedos musicais",
      "Detetive e espião"
    ],
    "Bricolage e artesanato": [
      "Suprimentos especializados faça você mesmo",
      "Fabricação de miçangas e joias",
      "Scrapbooking e estampagem",
      "Faça você mesmo carpintaria",
      "Olaria e cerâmica",
      "Tricô e crochê",
      "Suprimentos para pintura faça você mesmo",
      "Bordado",
      "Artesanato em feltro",
      "Confecção de crachás",
      "Fabricação de velas e sabonetes",
      "Artesanato em couro"
    ],
    "Brinquedos elétricos e de controle remoto": [
      "Carros, caminhões e trens",
      "Aviões e helicópteros",
      "Animais",
      "Tapetes de dança",
      "Máquinas de karaokê",
      "Walkie-talkies",
      "Motos",
      "Animais eletrônicos",
      "Barcos e submarinos",
      "Robôs",
      "Câmeras digitais",
      "Acessórios elétricos para brinquedos",
      "Tanques"
    ],
    "Instrumentos musicais e acessórios": [
      "Instrumentos de vento",
      "Acessórios musicais",
      "Guitarras e instrumentos de cordas",
      "Instrumentos de percussão",
      "Teclados e Pianos",
      "Bolsas e estojos para instrumentos",
      "Sintetizadores eletrônicos"
    ]
  },
  "Computadores e equipamentos de escritório": {
    "Artigos de papelaria e suprimentos para escritório": [
      "Material escolar e educacional",
      "Ferramentas de redação e correção",
      "Cadernos e papel",
      "Etiquetas, divisores de índice e selos",
      "Presentes e embalagens",
      "Crachás e suprimentos de identificação",
      "Calendários e acessórios",
      "Organizadores e acessórios de mesa",
      "Materiais de contabilidade",
      "Materiais de arte",
      "Produtos de arquivamento para escritório",
      "Envelopes e suprimentos postais",
      "Material de corte para escritório",
      "Cartões",
      "Material de medição para escritório",
      "Fita adesiva, adesivos e fixadores",
      "Material de encadernação para escritório",
      "Cofres",
      "Material de apresentação para escritório"
    ],
    "Armazenamento de dados e software": [
      "Unidades flash e cabos OTG",
      "Discos compactos",
      "SSD",
      "Cartões Micro SD",
      "Discos rígidos",
      "Estojos para discos rígidos e estações de encaixe",
      "Armazenamento conectado à rede"
    ],
    "Periféricos e acessórios": [
      "Suportes e bandejas para laptop",
      "Carregadores e adaptadores de laptop",
      "Teclados e mouses",
      "Tapetes para mouse",
      "Hubs USB e leitores de cartão",
      "Webcams",
      "Capas para teclado e trackpad",
      "Monitor portátil para computador",
      "Capas e estojos para laptop",
      "Almofadas de resfriamento",
      "Baterias para notebook"
    ],
    "Equipamentos de escritório": [
      "Limpadores para equipamentos de escritório",
      "Suprimentos para impressão 3D",
      "Peças de equipamento de escritório",
      "Impressoras de etiquetas",
      "Contadores de dinheiro",
      "Impressoras e scanners",
      "Cartuchos de tinta e toner",
      "Trituradores de papel",
      "Dispositivos de áudio e vídeo para conferência",
      "Laminadores",
      "Dispositivos de controle de acesso e atendimento",
      "Equipamento de impressão de anúncios",
      "Máquinas de fax",
      "Leitores de código de barras",
      "Máquinas de escrever",
      "Equipamento de varejo inteligente"
    ],
    "Componentes para desktop e laptop": [
      "Monitores",
      "Placas de som",
      "Unidades ópticas",
      "Cabos e acessórios",
      "Gabinete",
      "RAM",
      "Placas-mãe",
      "UPS e estabilizadores",
      "Ventiladores e dissipadores de calor",
      "Unidades de alimentação",
      "Placas gráficas",
      "Processadores",
      "Computadores de placa única (SBC)"
    ],
    "Componentes de rede": [
      "Cabos e conectores de rede",
      "Adaptadores sem fio e placas de rede",
      "Repetidores",
      "Modems e roteadores sem fio",
      "Chaves KVM",
      "Switches de rede e PoE",
      "Adaptadores powerline",
      "Servidores de impressão"
    ],
    "Computadores desktop, laptops e tablets": [
      "Laptops",
      "Computadores desktop",
      "Servidores",
      "Computadores All-in-One"
    ]
  },
  "Eletrodomésticos": {
    "Eletrodomésticos": [
      "Removedores de fiapos",
      "Ventiladores",
      "Peças de eletrodomésticos",
      "Esfregonas elétricas",
      "Aspiradores de pó e robôs varredores",
      "Lavadoras elétricas giratórias",
      "Purificadores de ar",
      "Limpa-vidros elétricos",
      "Umidificadores",
      "Vaporizadores de roupas",
      "Secadores de roupas e sapatos",
      "Esterilizadores domésticos",
      "Mata-mosquitos eletrônicos",
      "Ferros",
      "Cobertores elétricos",
      "Aquecedores",
      "Desumidificadores",
      "Secadores de mãos",
      "Secretárias eletrônicas",
      "Ar-condicionado",
      "Engraxadeiras elétricas",
      "Vapores elétricos"
    ],
    "Utensílios de cozinha": [
      "Peças para utensílios de cozinha",
      "Seladores a vácuo",
      "Processadores de alimentos",
      "Máquinas de café e acessórios",
      "Fritadeiras",
      "Misturadores",
      "Espremedores e liquidificadores",
      "Utensílios de cozinha especiais",
      "Churrasqueiras elétricas",
      "Arroz e panelas de pressão",
      "Refrigeradores e dispensadores de água",
      "Chaleiras elétricas",
      "Filtros de água",
      "Máquinas de fazer pão",
      "Torradeiras",
      "Fornos de bancada",
      "Panelas elétricas",
      "Placas de indução",
      "Micro-ondas",
      "Máquina de fazer refrigerante",
      "Trituradores de resíduos alimentares",
      "Máquina de fazer gelo"
    ],
    "Eletrodomésticos grandes": [
      "Ar-condicionados",
      "Peças e acessórios para eletrodomésticos grandes",
      "Máquinas de lavar e secadoras",
      "Geladeiras e freezers",
      "Televisores",
      "Aquecedores de água",
      "Máquinas de lavar louça",
      "Dispositivos de streaming de mídia",
      "Fornos, fogões e placas",
      "Exaustores",
      "Ar-condicionados portáteis"
    ],
    "Eletrodomésticos comerciais": [
      "Material de limpeza",
      "Equipamento de refrigeração",
      "Equipamento de ventilação e exaustão",
      "Equipamento de processamento de alimentos",
      "Peças de eletrodomésticos comerciais",
      "Fogões comerciais",
      "Equipamento de lavanderia"
    ]
  },
  "Esportes e atividades ao ar livre": {
    "Acessórios esportivos e para atividades ao ar livre": [
      "Fitas esportivas",
      "Equipamentos de proteção",
      "Mangas e suportes esportivos",
      "Bonés esportivos",
      "Óculos esportivos",
      "Bolsas esportivas",
      "Coberturas e máscaras faciais",
      "Luvas esportivas",
      "Garrafas esportivas",
      "Troféus, medalhas e prêmios",
      "Meias esportivas",
      "Pulseiras esportivas",
      "Equipamentos para treinadores e árbitros",
      "Tiaras esportivas",
      "Bolsas para sapatos",
      "Toalhas esportivas",
      "Cronômetros e temporizadores",
      "Equipamentos de campo e treinamento",
      "Giz",
      "Toucas de natação",
      "Pedômetros",
      "Equipamentos refletivos",
      "Armazenamento para bolas",
      "Coletes salva-vidas",
      "Protetores atléticos"
    ],
    "Roupas esportivas e para atividades ao ar livre": [
      "Calções esportivos",
      "Agasalhos",
      "Moletons esportivos",
      "Leggings esportivos",
      "Camisetas esportivas",
      "Coletes esportivos",
      "Macacões esportivos",
      "Vestidos esportivos",
      "Saias esportivas",
      "Sutiãs esportivos",
      "Calças jogger",
      "Camisetas de lycra",
      "Camisas",
      "Roupas esportivas infantis",
      "Roupa de banho infantil",
      "Roupa íntima esportiva",
      "Roupas esportivas impermeáveis",
      "Roupas íntimas esportivas térmicas",
      "Roupas e fantasias de dança",
      "Roupas com proteção solar"
    ],
    "Equipamento de ginástica": [
      "Treino com peso",
      "Treino abdominal",
      "Bambolês",
      "Máquinas de ginástica",
      "Barras de puxar",
      "Equipamentos de equilíbrio",
      "Fortalecedores de mãos",
      "Elásticos de resistência",
      "Acessórios para máquinas",
      "Trampolins",
      "Equipamentos de agilidade",
      "Bolas de ginástica",
      "Scooters e andadores",
      "Equipamentos de musculação",
      "Tapetes esportivos",
      "Cordas de pular",
      "Fitas de suspensão",
      "Ginástica aquática",
      "Tecnologia fitness",
      "Cintas de massagem e estimuladores elétricos"
    ],
    "Trajes de banho, surfe e natação": [
      "Moda praia",
      "Maiôs",
      "Biquínis",
      "Tanquínis",
      "Calções de banho",
      "Vestidos de natação",
      "Roupas de proteção para surfe",
      "Trajes de natação de alta performance",
      "Cuecas de banho",
      "Roupas de neoprene"
    ],
    "Calçados esportivos": [
      "Tênis de treino e academia",
      "Acessórios para calçados esportivos",
      "Sapatos de caminhada",
      "Tênis casual esportivo",
      "Calçados aquáticos",
      "Sapatos de trilha",
      "Sandálias esportivas",
      "Tênis de corrida",
      "Chuteiras",
      "Tênis de skate",
      "Sapatos de dança",
      "Tênis de basquete",
      "Sapatos de golfe",
      "Calçados esportivos infantis",
      "Botas para hipismo",
      "Chuteiras de futsal",
      "Patins",
      "Calçados para boxe",
      "Calçados para futebol americano",
      "Tênis para ciclismo",
      "Tênis de beisebol",
      "Calçados para atletismo",
      "Calçados para luta livre",
      "Calçados para yoga",
      "Tênis de badminton",
      "Calçados de cross-training",
      "Sapatilhas de escalada",
      "Tênis de voleibol"
    ],
    "Equipamentos para acampamento e caminhada": [
      "Binóculos e telescópios",
      "Iluminação para acampamento",
      "Utensílios para acampamento",
      "Purificação e armazenamento de água",
      "Redes",
      "Móveis para acampamento",
      "Kits de sobrevivência",
      "Tapetes e cestas de piquenique",
      "Tendas e acessórios",
      "Sacos de dormir",
      "Higiene para acampamento",
      "Bastões de caminhada",
      "Acendedores de fogo",
      "Equipamentos de segurança e sobrevivência",
      "Abrigos para acampamento",
      "Bolsas e mochilas",
      "Bússolas",
      "Impermeabilização e limpeza",
      "Sacos bivy",
      "Aquecedores de mãos e pés",
      "Carregadores infantis"
    ],
    "Equipamentos para esportes com bola": [
      "Golfe",
      "Beisebol",
      "Basquete",
      "Tênis de mesa",
      "Vôlei",
      "Futebol",
      "Tênis",
      "Softball",
      "Squash",
      "Futebol americano",
      "Sinuca",
      "Paddle",
      "Handebol",
      "Hóquei",
      "Lacrosse",
      "Badminton",
      "Rugby",
      "Boliche",
      "Polo",
      "Críquete",
      "Futsal",
      "Netball",
      "Racquetball"
    ],
    "Equipamentos para esportes aquáticos": [
      "Natação",
      "Mergulho",
      "Passeios de barco",
      "Surfe",
      "Kitesurf",
      "Caiaque",
      "Polo aquático",
      "Stand up paddle",
      "Vela",
      "Canoagem",
      "Remo",
      "Windsurf",
      "Esqui aquático e wakeboard"
    ],
    "Lazer e recreação ao ar livre": [
      "Hipismo",
      "Pesca",
      "Ciclismo",
      "Recreação indoor",
      "Yoga e Pilates",
      "Frisbee",
      "Corrida",
      "Ginástica",
      "Boxe e artes marciais",
      "Aeróbico",
      "Caça",
      "Dardos",
      "Skate",
      "Arco e flecha",
      "Alpinismo",
      "Balé e dança",
      "Motociclismo esportivo",
      "Animação de torcida",
      "Luta livre",
      "Esportes eletrônicos",
      "Karatê",
      "Patins",
      "Atletismo",
      "Taekwondo",
      "Paintball",
      "Triatlo",
      "Judô",
      "Esgrima"
    ],
    "Equipamentos para esportes de inverno": [],
    "Loja oficial": [],
    "Jogos de jardim": []
  },
  "Ferramentas e hardware": {
    "Ferramentas de medição": [
      "Instrumentos de medição física",
      "Instrumentos de medição de temperatura",
      "Ferramentas de medição manual",
      "Instrumentos ópticos",
      "Instrumentos de medição elétrica",
      "Instrumentos de medição de pressão"
    ],
    "Ferramentas elétricas": [
      "Acessórios para ferramentas elétricas",
      "Polidores",
      "Furadeiras elétricas",
      "Conjuntos de ferramentas elétricas",
      "Sopradores",
      "Chaves de fenda elétricas",
      "Ferramentas elétricas especiais",
      "Chaves elétricas",
      "Compressores de ar",
      "Serras elétricas",
      "Roteadores de madeira",
      "Pistolas de pintura",
      "Rebarbadoras",
      "Lavadoras de alta pressão",
      "Pistolas de cola",
      "Pistolas de pregos",
      "Armas de calor"
    ],
    "Ferramentas de jardim": [
      "Enxadas e ancinhos",
      "Acessórios para ferramentas de jardinagem",
      "Ferramentas de jardim especiais",
      "Ferramentas de limpeza de jardim",
      "Motosserras",
      "Cortadores de grama",
      "Ferramentas de poda",
      "Luvas e equipamentos de proteção para jardinagem",
      "Detectores de metal",
      "Sopradores de folhas e aspiradores",
      "Aparadores de grama",
      "Pás",
      "Garfos e colheres",
      "Ferramentas de remoção de neve"
    ],
    "Hardware": [
      "Adesivos, fitas e selantes",
      "Fechos e ganchos",
      "Ferragens para móveis",
      "Grampos",
      "Cadeados e ferrolhos",
      "Ferragens para porta",
      "Ímãs",
      "Produtos abrasivos e de acabamento",
      "Ferragens para janelas",
      "Cordas, correntes e polias",
      "Hardware mecânico"
    ],
    "Equipamento de solda": [
      "Acessórios de soldagem",
      "Soldadores",
      "Ferros de solda elétricos",
      "Estações de solda"
    ],
    "Ferramentas manuais": [
      "Alicates",
      "Chaves de fenda",
      "Ferramentas de corte",
      "Kits de ferramentas",
      "Chaves",
      "Multiferramentas e acessórios",
      "Rebitadores manuais",
      "Ferramentas manuais especiais",
      "Ferramentas de alvenaria e ladrilhos",
      "Tesouras",
      "Balanças industriais",
      "Pinças industriais",
      "Serras",
      "Acessórios para ferramentas manuais",
      "Facas",
      "Ferramentas de reparo de relógios",
      "Martelos",
      "Cinzéis",
      "Machados"
    ],
    "Bombas e encanamento": [
      "Tubos e conexões",
      "Válvulas e peças",
      "Bombas, peças e acessórios"
    ],
    "Organizadores de ferramentas": [
      "Bolsas de ferramentas",
      "Estojos e caixas de ferramentas",
      "Racks e barras de ferramentas"
    ]
  },
  "Joias, acessórios e derivados": {
    "Cristal natural": [
      "Pulseiras e tornozeleiras de cristal natural",
      "Decorações de cristais naturais",
      "Colares e pingentes de cristal natural",
      "Anéis de cristal natural",
      "Cristal natural semiacabado",
      "Conjuntos de joias de cristal natural",
      "Acessórios para roupas de cristal natural",
      "Brincos de cristal natural"
    ],
    "Pedras preciosas artificiais": [
      "Brincos de pedras preciosas artificiais",
      "Anéis de pedras preciosas artificiais",
      "Colares e pingentes de pedras preciosas artificiais",
      "Pulseiras e tornozeleiras de pedras preciosas artificiais",
      "Conjuntos de joias com pedras preciosas artificiais",
      "Acessórios para roupas com pedras preciosas artificiais"
    ],
    "Platina e ouro quilate": [
      "Anéis de platina e ouro",
      "Brincos de platina e ouro",
      "Pulseiras e tornozeleiras de platina e ouro",
      "Colares e pingentes de platina e ouro",
      "Conjuntos de joias de platina e ouro",
      "Acessórios para roupas de platina e ouro"
    ],
    "Prata": [
      "Anéis de prata",
      "Brincos de prata",
      "Decorações de prata",
      "Pulseiras e tornozeleiras de prata",
      "Colares e pingentes de prata",
      "Conjuntos de joias de prata",
      "Prata semiacabada",
      "Acessórios para roupas de prata"
    ],
    "Cristal artificial": [
      "Decorações de cristal artificial",
      "Pulseiras e tornozeleiras de cristal artificial",
      "Cristal artificial semiacabado",
      "Acessórios para roupas de cristal artificial",
      "Anéis de cristal artificial",
      "Colares e pingentes de cristal artificial",
      "Conjuntos de joias de cristal artificial",
      "Brincos de cristal artificial"
    ],
    "Jade": [
      "Pulseiras e tornozeleiras de jade",
      "Anéis de jade",
      "Decorações de jade",
      "Colares e pingentes de jade",
      "Conjuntos de joias de jade",
      "Brincos de jade",
      "Jade semiacabada",
      "Acessórios para roupas em jade"
    ],
    "Pedras semipreciosas": [
      "Pulseiras e tornozeleiras de pedras semipreciosas",
      "Anéis de pedras semipreciosas",
      "Pedras semipreciosas semiacabadas",
      "Colares e pingentes de pedras semipreciosas",
      "Conjuntos de joias com pedras semipreciosas",
      "Brincos de pedras semipreciosas",
      "Acessórios para roupas de pedras semipreciosas"
    ],
    "Pérola": [
      "Pérolas semiacabadas",
      "Brincos de pérola",
      "Colares e pingentes de pérola",
      "Pulseiras e tornozeleiras de pérola",
      "Acessórios para roupas de pérola",
      "Anéis de pérola",
      "Decorações de pérola",
      "Conjuntos de joias de pérola"
    ],
    "Âmbar": [
      "Colares e pingentes de âmbar",
      "Brincos âmbar",
      "Âmbar semiacabado",
      "Pulseiras e tornozeleiras de âmbar",
      "Decorações em âmbar",
      "Conjuntos de joias de âmbar",
      "Acessórios para roupas âmbar",
      "Anéis de âmbar"
    ],
    "Ouro": [
      "Colares e pingentes de ouro",
      "Anéis de ouro",
      "Brincos de ouro",
      "Pulseiras e tornozeleiras de ouro",
      "Decorações douradas",
      "Ouro semiacabado",
      "Conjuntos de joias de ouro"
    ],
    "Diamante": [
      "Anéis de diamante",
      "Conjuntos de joias com diamantes",
      "Colares e pingentes de diamantes",
      "Brincos de diamante",
      "Pulseiras e tornozeleiras de diamante",
      "Acessórios para roupas de diamante"
    ],
    "Rubi, safira e esmeralda": [
      "Conjuntos de joias de rubi, safira e esmeralda",
      "Pulseiras e tornozeleiras de rubi, safira e esmeralda",
      "Brincos de rubi, safira e esmeralda",
      "Anéis de rubi, safira e esmeralda",
      "Colares e pingentes de rubi, safira e esmeralda",
      "Rubi, safira e esmeralda semiacabados"
    ]
  },
  "Livros, revistas e áudios": {
    "Ciências humanas e sociais": [
      "Psicologia e relacionamentos",
      "Religião e filosofia",
      "Carreira e autoajuda",
      "Parentalidade e família",
      "História e cultura",
      "Política, direito e ciências sociais"
    ],
    "Estilo de vida e hobbies": [
      "Saúde, condicionamento físico e dieta",
      "Artesanato e bricolage",
      "Receitas e culinária",
      "Horóscopos",
      "Quadrinhos e mangá",
      "Esportes e condicionamento físico",
      "Moda e beleza",
      "Viagem e mapas",
      "Maternidade e educação pré-natal"
    ],
    "Literatura e arte": [
      "Biografias e memórias",
      "Literatura",
      "Ficção",
      "Pintura e design",
      "Fotografia e vídeo",
      "Música",
      "Artes performáticas",
      "Artes de cinema e televisão"
    ],
    "Educação e escolarização": [
      "Idioma e dicionários",
      "Livros didáticos",
      "Livros de aconselhamento"
    ],
    "Livros para bebês e infantis": [
      "Literatura e arte infantil",
      "Livros de atividades",
      "Livros de imagens",
      "Livros macios e de aprendizado de primeira infância",
      "Ciências humanas e sociais infantis",
      "Ciência e tecnologia infantil"
    ],
    "Economia e gestão": [
      "Finanças e Investimentos",
      "Gestão de negócios",
      "Economia"
    ],
    "Ciências e tecnologia": [
      "Arquitetura",
      "Médico",
      "Tecnologia industrial",
      "Agricultura, silvicultura e pesca",
      "Ciências naturais",
      "Computadores e redes"
    ],
    "Revistas e jornais": [
      "Estilo de vida",
      "Negócios",
      "Moda",
      "Adolescente"
    ],
    "Vídeo e música": [
      "Vinil",
      "CDs",
      "DVDs",
      "Fitas cassetes",
      "VHS"
    ]
  },
  "Malas e bolsas": {
    "Bolsas para mulheres": [
      "Sacolas",
      "Bolsas",
      "Carteiras",
      "Bolsas tiracolo e de ombro",
      "Clutches e pulseiras",
      "Pochetes",
      "Mochilas femininas",
      "Porta-cartões e documentos femininos",
      "Conjuntos de bolsas femininas"
    ],
    "Bolsas para homens": [
      "Carteiras",
      "Sacolas",
      "Bolsas tiracolo e de ombro",
      "Pochetes",
      "Clutches",
      "Porta-cartões e documentos masculinos",
      "Pastas",
      "Conjuntos de bolsas masculinas",
      "Mochilas masculinas"
    ],
    "Bolsas funcionais": [
      "Bolsas de maquiagem",
      "Lancheiras",
      "Bolsas para laptop",
      "Mochilas",
      "Bolsas de higiene",
      "Bolsas térmicas",
      "Sacolas de compras"
    ],
    "Malas e bolsas de viagem": [
      "Bagagem",
      "Bolsas de viagem",
      "Porta-passaportes e capas",
      "Organizadores de viagem",
      "Acessórios para bagagem"
    ],
    "Acessórios para bolsas": [
      "Organizadores de bolsas",
      "Decorações e lenços",
      "Alças e correntes para bolsas",
      "Cabides de bolsa",
      "Acessórios para bolsas DIY",
      "Limpeza e cuidados",
      "Capas para bolsas"
    ]
  },
  "Moda muçulmana": {
    "Hijabs": [
      "Lenços de baixo",
      "Hijabs instantâneos",
      "Lenços de pashmina",
      "Khimars",
      "Hijabs quadrados",
      "Niqab"
    ],
    "Roupas islâmicas femininas": [
      "Vestidos",
      "Vestes",
      "Kaftans",
      "Conjuntos de roupas",
      "Abayas",
      "Túnicas",
      "Camisas e blusas",
      "Macacões",
      "Roupas islâmicas femininas para dormir e ficar em casa",
      "Calças palazzo",
      "Saias",
      "Gamis",
      "Conjuntos de roupas para casais",
      "Leggings",
      "Punhos e peças internas"
    ],
    "Roupas islâmicas masculinas": [
      "Vestes",
      "Koko e tops",
      "Roupas islâmicas masculinas para dormir e ficar em casa",
      "Calças"
    ],
    "Acessórios islâmicos": [
      "Manguitos para mãos",
      "Alfinetes para hijab",
      "Meias"
    ],
    "Traje e equipamento de oração": [
      "Peci",
      "Tapetes para oração",
      "Conjuntos de oração",
      "Tasbih",
      "Vestimentas para oração",
      "Sarongue",
      "Mukena"
    ],
    "Roupas esportivas islâmicas": [
      "Agasalhos esportivos islâmicos",
      "Roupa de banho islâmica"
    ],
    "Agasalhos": [
      "Jaquetas",
      "Cardigãs",
      "Coletes",
      "Capas de chuva",
      "Casacos"
    ],
    "Roupas islâmicas infantis": [
      "Hijabs infantis",
      "Roupas islâmicas para meninas",
      "Roupas islâmicas para meninos"
    ],
    "Equipamento para umra": []
  },
  "Moda para crianças": {
    "Calçados para meninas": [
      "Chinelos",
      "Botas",
      "Sapatos baixos",
      "Tênis",
      "Sandálias e chinelos"
    ],
    "Roupas para meninos": [
      "Pijamas",
      "Meias",
      "Roupas íntimas",
      "Ternos e conjuntos",
      "Peças para parte inferior",
      "Fantasias e acessórios",
      "Peças para parte superior",
      "Casacos e jaquetas",
      "Uniformes escolares"
    ],
    "Roupas para meninas": [
      "Vestidos",
      "Ternos e conjuntos",
      "Peças para parte superior",
      "Pijamas",
      "Peças para parte inferior",
      "Casacos e jaquetas",
      "Fantasias e acessórios",
      "Roupas íntimas",
      "Saias",
      "Meias",
      "Meias-calças",
      "Uniformes escolares"
    ],
    "Acessórios de moda infantil": [
      "Óculos infantis",
      "Bolsas e bagagem para crianças",
      "Acessórios para cabelo infantil",
      "Chapéus infantis",
      "Relógios infantis",
      "Cachecóis e xales infantis",
      "Bijuterias e acessórios infantis",
      "Luvas infantis",
      "Gravatas e laços infantis",
      "Cintos infantis",
      "Protetores de ouvido infantis",
      "Máscaras faciais infantis"
    ],
    "Calçados para meninos": [
      "Sandálias e chinelos",
      "Sapatos baixos",
      "Tênis",
      "Chinelos",
      "Sapatos formais",
      "Botas"
    ]
  },
  "Móveis": {
    "Móveis comerciais": [
      "Móveis para escritório",
      "Móveis para hotel",
      "Móveis para salão",
      "Móveis para restaurante",
      "Móveis para escola"
    ],
    "Móveis para ambientes externos": [
      "Guarda-sóis",
      "Balanços de pátio",
      "Cadeiras para ambientes externos",
      "Conjuntos de móveis para ambientes externos",
      "Prateleiras externas",
      "Mesas para ambientes externos",
      "Banquetas e bancos",
      "Sofás para ambientes externos"
    ],
    "Móveis para ambientes internos": [
      "Suportes de TV e mesas de cabeceira",
      "Sofás",
      "Armários",
      "Mesas e escrivaninhas",
      "Estojos de maquiagem",
      "Estruturas e cabeceiras para cama",
      "Prateleiras e racks",
      "Colchões",
      "Cadeiras",
      "Banquetas e bancos",
      "Camas",
      "Conjuntos de móveis para ambientes internos",
      "Cabides",
      "Móveis para jogos",
      "Guarda-roupas",
      "Divisórias de espaço"
    ],
    "Móveis para crianças": [
      "Cadeiras",
      "Conjuntos de móveis",
      "Sofás",
      "Banquetas e bancos",
      "Prateleiras e racks",
      "Mesas e escrivaninhas",
      "Camas",
      "Armário",
      "Guarda-roupas",
      "Mesas de cabeceira",
      "Colchões"
    ]
  },
  "Reformas residenciais": {
    "Acessórios de banheiro": [
      "Equipamento de chuveiro",
      "Ganchos e barras",
      "Bidês e peças de bidê",
      "Espelhos para banheiro",
      "Acessórios para banheiro",
      "Banheiros e peças de banheiro",
      "Conjuntos para banheiro",
      "Pias de banheiro",
      "Torneiras de banheiro",
      "Banheiras",
      "Barras e assentos de segurança para banheiro"
    ],
    "Artigos de jardinagem": [
      "Cuidado e suporte de plantas",
      "Sementes",
      "Piscinas, banheiras de hidromassagem e suprimentos",
      "Decoração para jardim",
      "Vasos e jardineiras",
      "Rega e irrigação",
      "Flores frescas e plantas",
      "Edifícios de jardim",
      "Estufas e sementeiras",
      "Solo de jardim",
      "Jardins elevados",
      "Suprimentos para apicultura",
      "Aquecedores de pátio e fogueiras"
    ],
    "Luzes e Iluminação": [
      "Iluminação portátil",
      "Iluminação externa",
      "Iluminação interna",
      "Novidades em iluminação",
      "Acessórios de iluminação",
      "Lâmpadas, tubos e tiras",
      "Iluminação profissional",
      "Iluminação comercial"
    ],
    "Materiais de construção": [
      "Materiais e ferramentas para pintura",
      "Carrinhos",
      "Aquecimento, resfriamento e ventilação",
      "Telhados e pisos",
      "Portas, portões e janelas",
      "Papel de parede e acabamento de parede",
      "Escadas",
      "Ferramentas de papel de parede"
    ],
    "Acessórios de cozinha": [
      "Acessórios para utensílios de cozinha",
      "Torneiras de cozinha",
      "Dispositivos de filtragem de água",
      "Pias de cozinha",
      "Conjuntos de utensílios de cozinha",
      "Armários de cozinha"
    ],
    "Equipamentos e suprimentos elétricos": [
      "Tomadas elétricas e acessórios",
      "Motores, geradores e acessórios",
      "Economizadores de energia",
      "Conectores e terminais",
      "Relés e disjuntores",
      "Fios e cabos",
      "Suprimentos de energia",
      "Transformadores",
      "Interruptores e acessórios"
    ],
    "Segurança e proteção": [
      "Kits de emergência",
      "Campainhas e interfones",
      "Equipamentos de segurança do trabalho",
      "Alarmes de segurança"
    ],
    "Sistemas domésticos inteligentes": [
      "Controles de casa inteligente",
      "Sensores de movimento inteligentes",
      "Sistemas de controle de temperatura",
      "Sistemas automáticos de controle de cortinas"
    ],
    "Energia solar e eólica": [
      "Painéis solares",
      "Controladores de carga e acessórios",
      "Sistemas de energia solar",
      "Inversores de energia",
      "Turbinas eólicas"
    ]
  },
  "Roupas femininas e roupas íntimas femininas": {
    "Roupas íntimas femininas": [
      "Acessórios de sutiã",
      "Cinta modeladora",
      "Lingerie",
      "Calcinhas",
      "Bralettes",
      "Meias",
      "Meias-calças",
      "Conjuntos de roupas íntimas",
      "Roupas íntimas térmicas"
    ],
    "Ternos e macacões femininos": [
      "Ternos",
      "Macacões"
    ],
    "Vestidos femininos": [
      "Vestidos casuais",
      "Vestidos formais",
      "Vestidos de noiva",
      "Vestidos de madrinha"
    ],
    "Peças femininas para parte superior": [
      "Coletes, regatas e tops",
      "Blusas e camisas",
      "Camisetas",
      "Jaquetas e casacos",
      "Malhas",
      "Coletes",
      "Camisas polo"
    ],
    "Moda feminina de dormir e lazer": [
      "Camisolas",
      "Moletons e blusões",
      "Pijamas",
      "Macacão",
      "Roupões de banho"
    ],
    "Peças femininas para parte inferior": [
      "Jeans",
      "Shorts",
      "Calças",
      "Saias",
      "Saias-calças e Short-saias"
    ],
    "Roupas especiais para mulheres": [
      "Vestuário e uniformes",
      "Vestido tradicional"
    ],
    "Conjuntos de roupas para família": [],
    "Fantasias e acessórios": [],
    "Leggings": []
  },
  "Roupas masculinas e roupas íntimas masculinas": {
    "Peças masculinas para parte superior": [
      "Camisetas e regatas",
      "Camisetas",
      "Camisas polo",
      "Camisas",
      "Moletons e blusões",
      "Malhas",
      "Jaquetas e casacos",
      "Coletes"
    ],
    "Peças masculinas para parte inferior": [
      "Shorts",
      "Calças",
      "Jeans"
    ],
    "Ternos e macacões masculinos": [
      "Macacões"
    ],
    "Roupas íntimas masculinas": [
      "Roupas íntimas",
      "Roupas íntimas térmicas",
      "Modeladores masculinos"
    ],
    "Moda masculina de dormir e lazer": [
      "Pijamas",
      "Camisas de dormir",
      "Macacão"
    ],
    "Roupas especiais masculinas": [
      "Vestuário e uniformes de trabalho",
      "Fantasias e acessórios",
      "Vestido tradicional"
    ],
    "Conjuntos": [],
    "Ternos": [],
    "Meias": [],
    "Roupões, robes e macacões": []
  },
  "Sapatos": {
    "Acessórios para sapatos": [
      "Palmilhas e forros de calcanhar",
      "Protetores de sapatos e botas",
      "Cadarços",
      "Charms para decoração de sapatos",
      "Limpeza e cuidados",
      "Tensor de sapatos"
    ],
    "Sapatos femininos": [
      "Sapatos baixos",
      "Sandálias e chinelos",
      "Chinelos",
      "Sapatilhas sem cadarço",
      "Sapatos com salto",
      "Tênis",
      "Mules e tamancos",
      "Botas",
      "Calçados de trabalho e segurança",
      "Sapatos Mary Jane",
      "Oxfords",
      "Calçados tradicionais"
    ],
    "Sapatos masculinos": [
      "Tênis",
      "Calçados de trabalho e segurança",
      "Botas",
      "Mules e tamancos",
      "Sandálias e chinelos",
      "Chinelos",
      "Sapatilhas sem cadarço e sapatos baixos",
      "Oxfords",
      "Sapatos formais",
      "Sapatos para casamento",
      "Calçados tradicionais"
    ]
  },
  "Saúde": {
    "Suplementos alimentares": [
      "Suplementos de bem-estar",
      "Suplementos de beleza",
      "Suplementos herbais",
      "Suplementos fitness"
    ],
    "Medicamentos e tratamentos alternativos": [
      "Óleos essenciais e aromaterapia",
      "Fitoterapia"
    ],
    "Suprimentos médicos": [
      "Balanças de banheiro",
      "Sono e ronco",
      "Auxílios de medicamento",
      "Monitores e testes de saúde",
      "Termômetros",
      "Máscaras PPE",
      "Suprimentos de primeiros socorros",
      "Máscaras médicas",
      "Lenços desinfetantes",
      "Dispositivos de compressão corporal",
      "Suspensórios e suportes",
      "Bengalas"
    ]
  },
  "Suprimentos domésticos": {
    "Suprimentos para cuidados domésticos": [
      "Panos de limpeza",
      "Produtos de limpeza domésticos",
      "Rodos",
      "Esfregões",
      "Controle de pragas e ervas daninhas",
      "Fragrância para casa",
      "Espanadores e cabeças de espanador",
      "Rolos e panos de cozinha",
      "Papel higiênico e lenços umedecidos",
      "Esponjas e esfregões",
      "Lixeiras",
      "Protetores de sapato descartáveis",
      "Capas contra poeira",
      "Luvas de limpeza",
      "Protetores contra respingos",
      "Lenços, guardanapos e toalhetes",
      "Vassouras",
      "Sacos de lixo",
      "Aventais",
      "Baldes",
      "Proteção contra traças, mofo e umidade",
      "Removedores de formaldeído"
    ],
    "Suprimentos para banheiro": [
      "Tapetes de banho",
      "Cortinas e varões de chuveiro",
      "Toucas de banho",
      "Utensílios de banheiro",
      "Escovas de banheiro e desentupidores",
      "Porta-escovas de dentes",
      "Toalhas",
      "Capas para assento sanitário",
      "Dispensadores de sabão",
      "Conjuntos de banheiro",
      "Saboneteiras",
      "Lavatórios e escalda-pés",
      "Copos de banheiro"
    ],
    "Organizadores domésticos": [
      "Cabides e estacas",
      "Suportes e racks de armazenamento",
      "Ganchos e trilhos",
      "Sacos de armazenamento",
      "Cestas de armazenamento",
      "Caixas e recipientes de armazenamento"
    ],
    "Decoração de casa": [
      "Flores, plantas e frutas decorativas",
      "Decoração suspensa",
      "Velas",
      "Estátuas e estatuetas",
      "Placas e sinais",
      "Adesivos decorativos",
      "Ímãs de geladeira",
      "Leques",
      "Espelhos",
      "Ornamentos de Feng Shui",
      "Decorações religiosas",
      "Caixas de música",
      "Molduras de foto",
      "Cofrinhos",
      "Ganchos e prateleiras",
      "Castiçais",
      "Pôsteres e impressões",
      "Álbuns de fotos",
      "Relógios",
      "Tapeçarias"
    ],
    "Artigos festivos e para festas": [
      "Recortes de papelão",
      "Cenários e banners",
      "Decorações festivas",
      "Bolsas e presentes para festas",
      "Talheres descartáveis",
      "Balões",
      "Chapéus, máscaras e acessórios de festa",
      "Decorações de bolo",
      "Suprimentos para casamento",
      "Sprays, confetes e flâmulas",
      "Lanternas do céu"
    ],
    "Ferramentas e acessórios para lavanderia": [
      "Bolas e discos para lavar roupas",
      "Racks de secagem",
      "Sacos de lavagem",
      "Bordas metálicas",
      "Linhas de lavagem",
      "Cestos de lavanderia",
      "Lavatórios"
    ],
    "Garrafas e frascos de armazenamento": [],
    "Guarda-chuvas": [],
    "Vasos e enchimentos": [],
    "Variedades para casas": [
      "Garrafas de água quente",
      "Acessórios para isqueiros",
      "Lonas",
      "Botas Wellington",
      "Capas de chuva"
    ]
  },
  "Suprimentos para animais de estimação": {
    "Adestramento de cães e gatos": [
      "Produtos de remoção de pelos",
      "Toalhetes de tosa",
      "Pentes e escovas",
      "Cuidado oral",
      "Cuidados com garras",
      "Acessórios de banho",
      "Cuidados com os ouvidos",
      "Secadores de cabelo",
      "Máquinas de tosa",
      "Shampoos e condicionadores",
      "Tesouras de tosa",
      "Cuidados com os olhos",
      "Sprays e perfumes desodorizantes",
      "Géis e pós hemostáticos"
    ],
    "Areia para cães e gatos": [
      "Removedores de odores e manchas",
      "Bandejas e caixas de areia",
      "Fraldas, absorventes e bandejas",
      "Sacos de cocô e colheres",
      "Sistemas de treinamento de banheiro",
      "Detectores de urina"
    ],
    "Acessórios para cães e gatos": [
      "Brinquedos para gatos",
      "Brinquedos para cães",
      "Materiais de treinamento e comportamento",
      "Suprimentos de alimentação",
      "Coleiras, peitorais e guias",
      "Recordações para animais de estimação",
      "Transportadoras e suprimentos de viagem",
      "Câmeras e monitores"
    ],
    "Peixes e suprimentos aquáticos": [
      "Tratamento de água",
      "Ferramentas de limpeza",
      "Bombas e filtros",
      "Decorações",
      "Iluminação",
      "Ração para aquários",
      "Aquários e tanques",
      "Controle de temperatura",
      "Ferramentas de alimentação",
      "Suprimentos de nutrição e cuidados de saúde",
      "Medicamentos para aquários"
    ],
    "Saúde para cães e gatos": [
      "Vitaminas e suplementos",
      "Tratamentos para pulgas e carrapatos",
      "Coleiras e suportes de recuperação",
      "Medicamento"
    ],
    "Suprimentos para animais pequenos": [
      "Removedores de odores e manchas",
      "Transportadoras",
      "Ração para animais de estimação pequenos",
      "Roupas para animais de estimação pequenos",
      "Suprimentos de alimentação",
      "Brinquedos",
      "Casas e habitats",
      "Suprimentos de higiene",
      "Coleiras, arneses e trelas",
      "Suprimentos de saúde",
      "Rodas de exercício"
    ],
    "Roupas para cães e gatos": [
      "Camisas",
      "Acessórios para pescoço",
      "Chapéus",
      "Suéteres e moletons",
      "Vestidos",
      "Acessórios para cabelos",
      "Fantasias",
      "Casacos",
      "Botas e protetores de patas",
      "Capas de chuva",
      "Óculos",
      "Coletes salva-vidas"
    ],
    "Comida para cães e gatos": [
      "Petiscos para gatos",
      "Petiscos para cães",
      "Comida de cão",
      "Comida de gato"
    ],
    "Suprimentos para animais de fazenda e aves": [
      "Ferramentas de alimentação",
      "Operadoras e leads",
      "Gaiolas e acessórios",
      "Comida",
      "Marcação auricular",
      "Suprimentos de higiene",
      "Brinquedos",
      "Suprimentos de saúde para animais de fazenda"
    ],
    "Móveis para cães e gatos": [
      "Camas, sofás e tapetes",
      "Casas",
      "Almofadas e postes para arranhar",
      "Gaiolas e caixotes",
      "Cercados",
      "Redes para gatos",
      "Passagens para cães e gatos",
      "Escadas e rampas"
    ],
    "Suprimentos para pássaros": [
      "Ferramentas de alimentação",
      "Gaiolas e acessórios",
      "Brinquedos",
      "Suprimentos de higiene",
      "Balanços e poleiros",
      "Saúde das aves",
      "Materiais de treinamento",
      "Comida para pássaros"
    ],
    "Suprimentos para répteis e anfíbios": [
      "Terrários e suprimentos de remessa",
      "Ferramentas de limpeza",
      "Produtos para temperatura",
      "Decorações",
      "Comida para réptil",
      "Ferramentas de alimentação",
      "Iluminação",
      "Suprimentos de saúde para répteis"
    ]
  },
  "Telefones e eletrônicos": {
    "Acessórios para telefone": [
      "Suportes para telefone",
      "Capas e protetores de tela",
      "Baterias portáteis",
      "Cabos, carregadores e adaptadores",
      "Acessórios para selfie",
      "Peças de celular",
      "Baterias de telefone",
      "Alças e charms para telefone",
      "Lentes e flashes móveis"
    ],
    "Áudio e vídeo": [
      "Fones de ouvido",
      "Caixas de som",
      "Microfones",
      "Projetores",
      "Amplificadores e mixers",
      "Gravadores de voz",
      "Rádios",
      "Acessórios de áudio e vídeo",
      "Sistemas de cinema em casa"
    ],
    "Dispositivos inteligentes e tecnologia vestível": [
      "Smart watches",
      "Smart glasses",
      "Acessórios vestíveis",
      "Dispositivos de realidade virtual",
      "Rastreadores GPS",
      "Tecnologia para esporte"
    ],
    "Câmeras e fotografia": [
      "Acessórios para câmeras",
      "Câmeras de vídeo",
      "Câmeras de ação",
      "Drones e acessórios",
      "Câmeras instantâneas",
      "Lentes de câmera",
      "Câmeras sem espelho",
      "DSLRs"
    ],
    "Acessórios universais": [
      "Luzes USB portáteis",
      "Ventiladores USB portáteis",
      "Aspiradores USB",
      "Wi-Fi portátil",
      "Carregamento universal de bateria"
    ],
    "Jogos e consoles": [
      "Consoles de jogos domésticos",
      "Consoles portáteis",
      "Acessórios para console",
      "Videogames",
      "Acessórios para PC Gaming"
    ],
    "Telefones e tablets": [
      "Celulares",
      "Tablets",
      "Capas para tablets",
      "Carregadores para tablets",
      "Canetas stylus",
      "Suportes para tablets",
      "Teclados para tablets",
      "Protetores de tela para tablets"
    ],
    "Acessórios para tablets e computadores": [
      "Capas e estojos",
      "Carregadores e adaptadores",
      "Teclados",
      "Suportes e bases",
      "Peças e acessórios"
    ],
    "Eletrônicos recondicionados": [
      "Celulares recondicionados",
      "Tablets recondicionados",
      "Computadores e acessórios recondicionados",
      "Áudio e vídeo recondicionados",
      "Smart devices recondicionados"
    ],
    "Dispositivos de educação": [
      "Dicionários eletrônicos",
      "Dispositivos de aprendizagem",
      "Tablets de escrita",
      "Leitores digitais",
      "Canetas digitais",
      "Cadernos eletrônicos"
    ]
  },
  "Têxteis e móveis": {
    "Roupas de cama": [
      "Cobertores e mantas",
      "Colchões e colchonetes, pillow tops e capas protetoras",
      "Lençóis e fronhas",
      "Travesseiros e cunhas de cama",
      "Conjuntos de cama",
      "Edredons",
      "Acessórios de cama",
      "Colchas e Capas",
      "Saias de cama",
      "Capas de edredon",
      "Colchas",
      "Mosquiteiros",
      "Roupa de cama infantil",
      "Tapetes e almofadas de resfriamento"
    ],
    "Têxteis domésticos": [
      "Carpetes, tapetes e alcatifas",
      "Toalhas de mesa e corredores",
      "Almofadas, travesseiros e capas",
      "Cortinas",
      "Capas de sofá",
      "Capas de cadeira",
      "Capas contra poeira e armazenamento em tecido",
      "Camas infláveis, travesseiros e acessórios"
    ],
    "Tecidos e suprimentos de costura": [
      "Agulhas",
      "Kits de ferramentas de costura",
      "Máquinas de costura",
      "Acessórios de costura e retrosaria",
      "Kits de artesanato de costura",
      "Fio",
      "Têxteis e tecidos",
      "Tricô",
      "Bordado e conjuntos",
      "Crochê",
      "Feltro e conjuntos"
    ]
  },
  "Utensílios de cozinha": {
    "Utensílios para bebidas": [
      "Garrafas de água",
      "Garrafas térmicas",
      "Copos",
      "Acessórios para copos",
      "Canecas",
      "Chaleiras e jarras",
      "Xícaras e pires",
      "Garrafas de bolso"
    ],
    "Utensílios e aparelhos de cozinha": [
      "Descascadores e cortadores",
      "Outro",
      "Utensílios para carnes e aves",
      "Utensílios para frutas e vegetais",
      "Utensílios de medição",
      "Tupperware e utensílios para conservação de alimentos",
      "Temporizadores de cozinha",
      "Peneiras e escorredores",
      "Utensílios de cozinha",
      "Abridores de garrafa",
      "Distribuidores de óleo",
      "Termômetros de cozinha",
      "Utensílios para sorvete",
      "Utensílios para frutos do mar",
      "Utensílios para temperar",
      "Utensílios de ovo",
      "Utensílios de bebida",
      "Iniciadores de fogo",
      "Utensílios para massas e pizzas"
    ],
    "Utensílios para forno": [
      "Utensílios para assar",
      "Tabuleiros",
      "Assadeiras",
      "Ferramentas de decoração",
      "Assadeiras e moldes",
      "Luvas de forno"
    ],
    "Facas de cozinha": [
      "Blocos de facas e armazenamento",
      "Conjuntos de blocos de facas",
      "Tesouras de cozinha",
      "Tábuas de cortar",
      "Facas de cozinha",
      "Amoladores de facas"
    ],
    "Utensílios para cozinhar": [
      "Panelas e woks",
      "Conjuntos de panelas",
      "Panelas de pressão",
      "Panelas",
      "Panelas descartáveis",
      "Acessórios para panelas",
      "Vaporizadores"
    ],
    "Utensílios para bares e vinhos": [
      "Utensílios de bar",
      "Equipamento para fazer vinho",
      "Conjuntos de bar",
      "Prateleiras para vinhos"
    ],
    "Talheres e serviços de mesa": [
      "Faqueiros",
      "Lancheiras",
      "Jogos americanos e porta-copos",
      "Descansos de talheres",
      "Colheres",
      "Tigelas",
      "Facas",
      "Pratos",
      "Garfos",
      "Guardanapos",
      "Hashis"
    ],
    "Churrasco": [
      "Utensílios para churrasco",
      "Churrascos"
    ],
    "Utensílios para chá e café": [
      "Ferramentas para fazer chá",
      "Jogos de chá",
      "Filtros de café",
      "Cafeteiras",
      "Bules",
      "Moedores manuais de café",
      "Jarras de leite",
      "Ferramentas para fazer café",
      "Jogos de café"
    ]
  }
};
